### ISSUE TITLE
举例

### ISSUE THREAD

**Issue by hp-luo** [Duconnor/SearchEngine#2]
实习生
find in 2 pages
No. 1 result  【言论】在中国大学生骨干培养学校第六期结业暨第七期开班式上的讲话 with indegree 0
No. 1 result https://tuanwei.nju.edu.cn/article/1767-2013-12-29-09-14-27.html with indegree 0
No. 2 result  【人物】祝贺我校商院学子在全国大学生银行产品创意设计大赛中斩获佳绩 with indegree 0
No. 2 result https://tuanwei.nju.edu.cn/article/1750-2013-12-27-04-33-24.html with indegree 0
比如上面这样，博主能不能给我演示一遍呢

**Comment by Duconnor** [comment]
你是说上面这个结果不准确吗

**Comment by Duconnor** [comment]
I'll close this issue due to its inactivity. Feel free to reopen it if you need to post anything new.
